version: '3.7'

services:
  jobs:
    build: .
    command: gunicorn job_board.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
  db:
    image: postgres:12.0-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jobs_user
      - POSTGRES_PASSWORD=jobs_password
      - POSTGRES_DB=jobs
    expose:
      - 5432

volumes:
  postgres_data:
