version: '3.7'

services:
  jobs:
    build: .
    command: gunicorn job_board.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/home/app/web
    expose:
      - 8000
  db:
    image: postgres:12.0-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jobs_user
      - POSTGRES_PASSWORD=jobs_password
      - POSTGRES_DB=jobs
    expose:
      - 5432
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - jobs

volumes:
  postgres_data:
  static_volume:
  media_volume:
